// UNITY-DEPENDENT — requires the Unity Editor (UnityEditor + JsonUtility).
// Converts versioned Content/*.json into ScriptableObjects under
// Assets/Scripts/Runtime/Generated/. JSON is the source of truth; generated
// .asset files are git-ignored and regenerated by CI and by Beth.
//
// AI agents: this script may CREATE assets via AssetDatabase, but NEVER hand-edit
// scene/prefab YAML or GUIDs.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using ScandalSeason.Domain.Economy; // GameRules: chapters/season, scenes/chapter

public static class ContentImporter
{
    public const string ExpectedSchemaVersion = "1.0.0";
    private const string GeneratedRoot = "Assets/Scripts/Runtime/Generated";

    // ------------------------------------------------------------------ menu

    [MenuItem("Scandal Season/Import Content JSON")]
    public static void ImportAll()
    {
        var errors = new List<string>();
        string contentDir = ContentDirectory();

        ImportMergeChains(contentDir, errors);
        ImportOutfits(contentDir, errors);
        ImportScenes(contentDir, errors);
        ImportVoteEvents(contentDir, errors);
        ImportSeasonPasses(contentDir, errors);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        if (errors.Count > 0)
        {
            foreach (var e in errors) Debug.LogError($"[Content] {e}");
            Debug.LogError($"[Content] Import finished with {errors.Count} error(s). Fix Content/*.json and re-import.");
        }
        else
        {
            Debug.Log("[Content] Import complete — all files valid.");
        }

        ExitBatchMode(errors.Count);
    }

    [MenuItem("Scandal Season/Validate Content JSON")]
    public static void ValidateOnly()
    {
        var errors = new List<string>();
        string contentDir = ContentDirectory();

        ValidateFile<MergeChainsFile>(contentDir, "merge-chains.json", errors, ValidateMergeChains);
        ValidateFile<OutfitsFile>(contentDir, "outfits.json", errors, ValidateOutfits);
        ValidateFile<ScenesFile>(contentDir, "scenes.json", errors, ValidateScenes);
        ValidateFile<ScenesFile>(contentDir, "scenes-season2.json", errors, ValidateScenes);
        ValidateFile<ScenesFile>(contentDir, "scenes-season3.json", errors, ValidateScenes);
        ValidateFile<VoteEventsFile>(contentDir, "vote-events.json", errors, ValidateVoteEvents);
        ValidateFile<SeasonPassesFile>(contentDir, "season-passes.json", errors, ValidateSeasonPasses);

        if (errors.Count > 0)
        {
            foreach (var e in errors) Debug.LogError($"[Content] {e}");
            Debug.LogError($"[Content] Validation failed with {errors.Count} error(s).");
        }
        else Debug.Log("[Content] All content files valid.");

        ExitBatchMode(errors.Count);
    }

    // In -batchmode (CI / headless runs), surface failures as a non-zero exit
    // code so automation can fail the job. Never quits the interactive editor.
    private static void ExitBatchMode(int errorCount)
    {
        if (Application.isBatchMode)
            EditorApplication.Exit(errorCount > 0 ? 1 : 0);
    }

    // ------------------------------------------------------------------ io

    private static string ContentDirectory()
    {
        string dir = Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Content"));
        if (!Directory.Exists(dir))
            throw new DirectoryNotFoundException($"Content directory not found: {dir}");
        return dir;
    }

    private static T ReadJson<T>(string contentDir, string fileName, List<string> errors) where T : class
    {
        string path = Path.Combine(contentDir, fileName);
        if (!File.Exists(path))
        {
            errors.Add($"{fileName}: file not found.");
            return null!;
        }
        try
        {
            var parsed = JsonUtility.FromJson<T>(File.ReadAllText(path));
            if (parsed == null) errors.Add($"{fileName}: parsed to null (malformed JSON?).");
            return parsed!;
        }
        catch (Exception ex)
        {
            errors.Add($"{fileName}: JSON parse error: {ex.Message}");
            return null!;
        }
    }

    private static bool CheckSchemaVersion(string fileName, string schemaVersion, List<string> errors, string expected = ExpectedSchemaVersion)
    {
        if (schemaVersion != expected)
        {
            errors.Add($"{fileName}: schemaVersion '{schemaVersion}' != expected '{expected}'.");
            return false;
        }
        return true;
    }

    // Dotted ids namespace content to its board/area (e.g. atelier.notions).
    // The literal "TBD" marks design placeholders the importer skips.
    private static readonly Regex IdPattern = new Regex(@"^([a-z0-9._-]+|TBD)$", RegexOptions.Compiled);

    private static bool CheckId(string fileName, string id, List<string> errors, string what)
    {
        if (string.IsNullOrEmpty(id) || !IdPattern.IsMatch(id))
        {
            errors.Add($"{fileName}: {what} has invalid id '{id}' (must match ^([a-z0-9._-]+|TBD)$).");
            return false;
        }
        return true;
    }

    private static bool CheckSeason(string fileName, string id, int season, List<string> errors)
    {
        // Seasons are endless (Book One is 1–10); only the lower bound is enforced.
        if (season < 1)
        {
            errors.Add($"{fileName}: '{id}' season {season} out of range (must be >= 1).");
            return false;
        }
        return true;
    }

    private static void ValidateFile<T>(string contentDir, string fileName, List<string> errors, Action<string, T, List<string>> validate) where T : class
    {
        var parsed = ReadJson<T>(contentDir, fileName, errors);
        if (parsed != null) validate(fileName, parsed, errors);
    }

    private static string EnsureFolder(string folder)
    {
        if (AssetDatabase.IsValidFolder(folder)) return folder;
        string parent = Path.GetDirectoryName(folder)!.Replace('\\', '/');
        EnsureFolder(parent);
        AssetDatabase.CreateFolder(parent, Path.GetFileName(folder));
        return folder;
    }

    private static string SanitizeAssetName(string id) =>
        Regex.Replace(id, @"[^a-zA-Z0-9-_]", "_");

    private static void SaveDefinition<T>(string subfolder, string id, T asset) where T : ScriptableObject
    {
        string folder = EnsureFolder($"{GeneratedRoot}/{subfolder}");
        string path = $"{folder}/{SanitizeAssetName(id)}.asset";
        if (AssetDatabase.LoadAssetAtPath<T>(path) != null)
            AssetDatabase.DeleteAsset(path);
        AssetDatabase.CreateAsset(asset, path);
    }

    // ------------------------------------------------------------------ merge chains

    [Serializable] private sealed class MergeChainsFile
    {
        public string schemaVersion = "";
        public MergeChainDto[] chains = Array.Empty<MergeChainDto>();
    }
    [Serializable] private sealed class MergeChainDto
    {
        public string id = "";
        public string board = "";
        public string displayName = "";
        public ChainLevelDto[] levels = Array.Empty<ChainLevelDto>();
    }
    [Serializable] private sealed class ChainLevelDto
    {
        public int level;
        public string itemId = "";
        public string name = "";
        public string displayName = "";
        public string artHook = "";
        public string art_notes = "";
        public int baseValue;
        public int unlockSeason = 1;
    }

    private static void ValidateMergeChains(string fileName, MergeChainsFile file, List<string> errors)
    {
        // Design files may not carry a schema version yet — warn, don't fail.
        if (string.IsNullOrEmpty(file.schemaVersion))
            Debug.LogWarning($"[Content] {fileName}: no schemaVersion; assuming {ExpectedSchemaVersion}.");
        else if (file.schemaVersion != ExpectedSchemaVersion)
            Debug.LogWarning($"[Content] {fileName}: schemaVersion '{file.schemaVersion}' != expected '{ExpectedSchemaVersion}'.");
        if (file.chains.Length == 0) errors.Add($"{fileName}: at least one chain is required.");
        var seenIds = new System.Collections.Generic.HashSet<string>();
        var seenItemIds = new System.Collections.Generic.HashSet<string>();
        foreach (var chain in file.chains)
        {
            if (chain.id == "TBD")
            {
                Debug.Log($"[Content] {fileName}: skipping TBD chain '{chain.displayName}' (no id assigned yet).");
                continue;
            }
            if (!CheckId(fileName, chain.id, errors, "chain")) continue;
            if (!seenIds.Add(chain.id))
                errors.Add($"{fileName}: duplicate chain id '{chain.id}'.");
            if (string.IsNullOrWhiteSpace(chain.displayName))
                errors.Add($"{fileName}: chain '{chain.id}' needs a displayName.");
            if (chain.levels.Length != 10)
                errors.Add($"{fileName}: chain '{chain.id}' must have exactly 10 levels (locked engine rule; found {chain.levels.Length}).");
            for (int i = 0; i < chain.levels.Length; i++)
            {
                var lvl = chain.levels[i];
                if (lvl.level != i + 1)
                    errors.Add($"{fileName}: chain '{chain.id}' levels must be sequential from 1 (found {lvl.level} at index {i}).");
                if (string.IsNullOrWhiteSpace(lvl.itemId))
                    errors.Add($"{fileName}: chain '{chain.id}' level {lvl.level} needs an itemId.");
                else if (!seenItemIds.Add(lvl.itemId))
                    errors.Add($"{fileName}: duplicate itemId '{lvl.itemId}' (chain '{chain.id}' level {lvl.level}).");
                if (string.IsNullOrWhiteSpace(lvl.name) && string.IsNullOrWhiteSpace(lvl.displayName))
                    errors.Add($"{fileName}: chain '{chain.id}' level {lvl.level} needs a name.");
                CheckSeason(fileName, $"{chain.id} level {lvl.level}", lvl.unlockSeason, errors);
            }
        }
    }

    private static void ImportMergeChains(string contentDir, List<string> errors)
    {
        var file = ReadJson<MergeChainsFile>(contentDir, "merge-chains.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateMergeChains("merge-chains.json", file, errors);
        if (errors.Count != before) return;
        // Content set changed (placeholder chains replaced by design chains):
        // clear previously generated chain assets so stale ones can't linger.
        foreach (var guid in AssetDatabase.FindAssets("", new[] { $"{GeneratedRoot}/MergeChains" }))
            AssetDatabase.DeleteAsset(AssetDatabase.GUIDToAssetPath(guid));
        foreach (var chain in file.chains)
        {
            if (chain.id == "TBD") continue; // logged in validation
            var so = ScriptableObject.CreateInstance<ItemChainDefinitionSO>();
            so.chainId = chain.id;
            so.board = chain.board;
            so.displayName = chain.displayName;
            so.levels = Array.ConvertAll(chain.levels, l => new ItemChainDefinitionSO.ChainLevel
            {
                level = l.level,
                itemId = l.itemId,
                displayName = !string.IsNullOrWhiteSpace(l.name) ? l.name
                    : !string.IsNullOrWhiteSpace(l.displayName) ? l.displayName
                    : $"TBD (level {l.level})",
                artHook = l.artHook,
                artNotes = l.art_notes,
                baseValue = l.baseValue,
                unlockSeason = l.unlockSeason
            });
            SaveDefinition("MergeChains", chain.id, so);
        }
    }

    // ------------------------------------------------------------------ outfits
    // Wardrobe v2 (locked Sep 27 2026): dual-unit wardrobe. Ensembles are the
    // Daily Vote (competition-side) unit; components are the chapter-dressing
    // (story-side) unit. Rarity: atelier / couture / imperiale / legende.

    [Serializable] private sealed class OutfitsFile
    {
        public string schemaVersion = "";
        public OutfitCollectionDto[] collections = Array.Empty<OutfitCollectionDto>();
        public EnsembleDto[] ensembles = Array.Empty<EnsembleDto>();
    }
    [Serializable] private sealed class OutfitCollectionDto
    {
        public string collectionId = "";
        public string title = "";
        public int group = 1;
        public string occasion = "";
        public string theme = "";
    }
    [Serializable] private sealed class EnsembleDto
    {
        public string id = "";
        public string collectionId = "";
        public string name = "";
        public string rarity = "";
        public bool timeless;
        public bool time_only; // legacy alias of timeless; either flag marks a time-only ensemble
        public ModisteDto modiste = new ModisteDto();
        public string story = "";
        public EnsembleComponentDto[] components = Array.Empty<EnsembleComponentDto>();
        public string portrait_moment = "";
        public string harmony_bonus = "";
        public OutfitAcquisitionDto acquisition = new OutfitAcquisitionDto();
    }
    [Serializable] private sealed class ModisteDto
    {
        public string name = "";
        public string voice = "";
    }
    [Serializable] private sealed class EnsembleComponentDto
    {
        public string id = "";
        public string name = "";
        public string ritual_part = "";
        public string lore = "";
        public ColorwayDto colorways = new ColorwayDto();
    }
    [Serializable] private sealed class ColorwayDto
    {
        public ColorwayBaseDto @base = new ColorwayBaseDto();
        public ColorwayRecolorDto recolor = new ColorwayRecolorDto();
        public string[] dye_palette = Array.Empty<string>();
    }
    [Serializable] private sealed class ColorwayBaseDto
    {
        public string fabric = "";
        public string color = "";
    }
    [Serializable] private sealed class ColorwayRecolorDto
    {
        public string name = "";
        public string fabric = "";
        public string color = "";
    }
    [Serializable] private sealed class OutfitAcquisitionDto
    {
        public string free_path = "";
        public string crowns_path = "";
    }

    private static readonly System.Collections.Generic.HashSet<string> OutfitRarities =
        new System.Collections.Generic.HashSet<string> { "atelier", "couture", "imperiale", "legende" };

    private static void ValidateOutfits(string fileName, OutfitsFile file, List<string> errors)
    {
        // Design files may not carry a schema version yet — warn, don't fail.
        if (string.IsNullOrEmpty(file.schemaVersion))
            Debug.LogWarning($"[Content] {fileName}: no schemaVersion; assuming {ExpectedSchemaVersion}.");
        else if (file.schemaVersion != ExpectedSchemaVersion)
            Debug.LogWarning($"[Content] {fileName}: schemaVersion '{file.schemaVersion}' != expected '{ExpectedSchemaVersion}'.");
        var collectionIds = new System.Collections.Generic.HashSet<string>();
        foreach (var c in file.collections)
        {
            if (!CheckId(fileName, c.collectionId, errors, "collection")) continue;
            collectionIds.Add(c.collectionId);
            if (string.IsNullOrWhiteSpace(c.title))
                errors.Add($"{fileName}: collection '{c.collectionId}' needs a title.");
        }
        if (file.ensembles.Length == 0)
            errors.Add($"{fileName}: at least one ensemble is required.");
        var seenIds = new System.Collections.Generic.HashSet<string>();
        var seenComponentIds = new System.Collections.Generic.HashSet<string>();
        foreach (var ensemble in file.ensembles)
        {
            if (ensemble.id == "TBD")
            {
                Debug.Log($"[Content] {fileName}: skipping TBD ensemble '{ensemble.name}' (no id assigned yet).");
                continue;
            }
            if (!CheckId(fileName, ensemble.id, errors, "ensemble")) continue;
            if (!seenIds.Add(ensemble.id))
                errors.Add($"{fileName}: duplicate ensemble id '{ensemble.id}'.");
            if (string.IsNullOrWhiteSpace(ensemble.name))
                errors.Add($"{fileName}: ensemble '{ensemble.id}' needs a name.");
            if (!collectionIds.Contains(ensemble.collectionId))
                errors.Add($"{fileName}: ensemble '{ensemble.id}' references unknown collection '{ensemble.collectionId}'.");
            if (!OutfitRarities.Contains(ensemble.rarity))
                errors.Add($"{fileName}: ensemble '{ensemble.id}' has unknown rarity '{ensemble.rarity}'.");
            if (string.IsNullOrWhiteSpace(ensemble.modiste?.name))
                errors.Add($"{fileName}: ensemble '{ensemble.id}' needs a modiste name.");
            if (ensemble.components.Length == 0)
                errors.Add($"{fileName}: ensemble '{ensemble.id}' needs at least one component.");
            foreach (var comp in ensemble.components)
            {
                if (!CheckId(fileName, comp.id, errors, "component")) continue;
                if (!seenComponentIds.Add(comp.id))
                    errors.Add($"{fileName}: duplicate component id '{comp.id}'.");
                if (string.IsNullOrWhiteSpace(comp.name))
                    errors.Add($"{fileName}: component '{comp.id}' needs a name.");
                if (string.IsNullOrWhiteSpace(comp.ritual_part))
                    errors.Add($"{fileName}: component '{comp.id}' needs a ritual_part.");
            }
            if (ensemble.acquisition == null || string.IsNullOrWhiteSpace(ensemble.acquisition.free_path))
                errors.Add($"{fileName}: ensemble '{ensemble.id}' needs an acquisition free_path.");
        }
    }

    private static void ImportOutfits(string contentDir, List<string> errors)
    {
        var file = ReadJson<OutfitsFile>(contentDir, "outfits.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateOutfits("outfits.json", file, errors);
        if (errors.Count != before) return;
        // Content set changed (v1 outfits replaced by v2 ensembles):
        // clear previously generated outfit assets so stale ones can't linger.
        foreach (var guid in AssetDatabase.FindAssets("", new[] { $"{GeneratedRoot}/Outfits" }))
            AssetDatabase.DeleteAsset(AssetDatabase.GUIDToAssetPath(guid));
        foreach (var ensemble in file.ensembles)
        {
            if (ensemble.id == "TBD") continue; // logged in validation
            var so = ScriptableObject.CreateInstance<OutfitDefinitionSO>();
            so.outfitId = ensemble.id;
            so.displayName = ensemble.name;
            so.collectionId = ensemble.collectionId;
            so.rarity = ensemble.rarity;
            so.season = 1; // Group 1 is Season 1 content; later groups map to seasons when designed
            so.timeless = ensemble.timeless || ensemble.time_only;
            so.modisteName = ensemble.modiste?.name ?? "";
            so.modisteVoice = ensemble.modiste?.voice ?? "";
            so.ensembleStory = ensemble.story ?? "";
            so.portraitMoment = ensemble.portrait_moment ?? "";
            so.harmonyBonus = ensemble.harmony_bonus ?? "";
            so.components = System.Array.ConvertAll(ensemble.components, c =>
                new OutfitDefinitionSO.OutfitComponent
                {
                    componentId = c.id,
                    displayName = c.name ?? "",
                    ritualPart = c.ritual_part ?? "",
                    lore = c.lore ?? "",
                    baseFabric = c.colorways?.@base?.fabric ?? "",
                    baseColor = c.colorways?.@base?.color ?? "",
                    recolorName = c.colorways?.recolor?.name ?? "",
                    recolorFabric = c.colorways?.recolor?.fabric ?? "",
                    recolorColor = c.colorways?.recolor?.color ?? "",
                    dyePalette = c.colorways?.dye_palette ?? System.Array.Empty<string>()
                });
            so.acquisition = new OutfitDefinitionSO.OutfitAcquisition
            {
                freePath = ensemble.acquisition.free_path,
                crownsPath = ensemble.acquisition.crowns_path
            };
            SaveDefinition("Outfits", ensemble.id, so);
        }
    }

    // ------------------------------------------------------------------ scenes

    [Serializable] private sealed class ScenesFile
    {
        public string schemaVersion = "";
        public int season = 1;
        public SceneDto[] scenes = Array.Empty<SceneDto>();
    }
    [Serializable] private sealed class DecisionOptionDto
    {
        public string label = "";
        public string detail = "";
    }
    [Serializable] private sealed class KeyDecisionDto
    {
        public int number;
        public string title = "";
        public DecisionOptionDto[] options = Array.Empty<DecisionOptionDto>();
    }
    [Serializable] private sealed class RitualDto
    {
        public string part = "";
        public string occasionBrief = "";
        public string[] directions = Array.Empty<string>();
        public string stepsSummary = "";
        public string[] steps = Array.Empty<string>();
        public int coinPerDecision;
        public int coinTotal;
    }
    [Serializable] private sealed class FashionChoiceDto
    {
        public string label = "";
        public string detail = "";
    }
    [Serializable] private sealed class SceneDto
    {
        public string id = "";
        public int season = 1;
        public int chapter = 1;
        public int scene = 1;
        public string chapterTitle = "";
        public string chapterStatus = "";
        public string type = "";
        public string synopsis = "";
        public string[] participants = Array.Empty<string>();
        public string animation = "";
        public string animationNote = "";
        public string beatQualifier = "";
        public int playerTurns;
        public string turnNote = "";
        // Null when the scene carries no key decision / ritual / sting (optional JSON objects).
        public KeyDecisionDto keyDecision;
        public RitualDto ritual;
        public FashionChoiceDto[] fashionChoices;
        public string sting;
        public string sourceFile = "";
    }

    private static SceneType ParseSceneType(string type) => type switch
    {
        "dialogue" => SceneType.Dialogue,
        "fashion-selection" => SceneType.FashionSelection,
        "chapter-climax" => SceneType.ChapterClimax,
        "texture" => SceneType.Texture,
        "plot-beat" => SceneType.PlotBeat,
        "gazette-sting" => SceneType.GazetteSting,
        "cliffhanger" => SceneType.Cliffhanger,
        _ => throw new ArgumentException($"Unknown scene type '{type}'.")
    };

    private static SceneAnimation ParseSceneAnimation(string animation) => animation switch
    {
        "Shared" => SceneAnimation.Shared,
        "Custom" => SceneAnimation.Custom,
        _ => throw new ArgumentException($"Unknown scene animation '{animation}'.")
    };

    private const string ScenesSchemaVersion = "2.1.0";

    // NOTE: JsonUtility instantiates nested [Serializable] DTO objects even when the
    // JSON key is absent, so presence is detected by content, not by null.
    private static bool HasKeyDecision(SceneDto scene) =>
        scene.keyDecision != null && !string.IsNullOrWhiteSpace(scene.keyDecision.title);
    private static bool HasRitual(SceneDto scene) =>
        scene.ritual != null && (!string.IsNullOrWhiteSpace(scene.ritual.occasionBrief)
            || (scene.ritual.directions != null && scene.ritual.directions.Length > 0)
            || (scene.ritual.steps != null && scene.ritual.steps.Length > 0)
            || !string.IsNullOrWhiteSpace(scene.ritual.part));

    private static void ValidateScenes(string fileName, ScenesFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors, ScenesSchemaVersion)) return;
        if (file.scenes.Length == 0) errors.Add($"{fileName}: at least one scene is required.");
        foreach (var scene in file.scenes)
        {
            if (!CheckId(fileName, scene.id, errors, "scene")) continue;
            CheckSeason(fileName, scene.id, scene.season, errors);
            if (scene.chapter < 1 || scene.chapter > GameRules.ChaptersPerSeason)
                errors.Add($"{fileName}: scene '{scene.id}' chapter {scene.chapter} out of range (1–{GameRules.ChaptersPerSeason}).");
            if (scene.scene < 1 || scene.scene > GameRules.ScenesPerChapter)
                errors.Add($"{fileName}: scene '{scene.id}' scene number {scene.scene} out of range (1–{GameRules.ScenesPerChapter}).");
            if (string.IsNullOrWhiteSpace(scene.chapterTitle))
                errors.Add($"{fileName}: scene '{scene.id}' needs a chapterTitle.");
            if (scene.chapterStatus != "FULL" && scene.chapterStatus != "PILOT")
                errors.Add($"{fileName}: scene '{scene.id}' chapterStatus '{scene.chapterStatus}' must be FULL or PILOT.");
            SceneType parsed;
            try { parsed = ParseSceneType(scene.type); }
            catch { errors.Add($"{fileName}: scene '{scene.id}' has unknown type '{scene.type}'."); continue; }
            try { ParseSceneAnimation(scene.animation); }
            catch { errors.Add($"{fileName}: scene '{scene.id}' has unknown animation '{scene.animation}'."); }
            if (parsed == SceneType.ChapterClimax && !HasRitual(scene))
                errors.Add($"{fileName}: chapter-climax scene '{scene.id}' requires ritual content (brief, directions, steps, or part label).");
            if (parsed == SceneType.GazetteSting && string.IsNullOrWhiteSpace(scene.sting))
                errors.Add($"{fileName}: gazette-sting scene '{scene.id}' requires sting text.");
            if (parsed == SceneType.FashionSelection && scene.fashionChoices == null)
                errors.Add($"{fileName}: fashion-selection scene '{scene.id}' requires fashionChoices (may be empty).");
            if (HasKeyDecision(scene))
            {
                if (scene.keyDecision.number < 1 || scene.keyDecision.number > 3)
                    errors.Add($"{fileName}: scene '{scene.id}' key decision number {scene.keyDecision.number} out of range (1–3).");
                if (string.IsNullOrWhiteSpace(scene.keyDecision.title))
                    errors.Add($"{fileName}: scene '{scene.id}' key decision needs a title.");
                if (scene.keyDecision.options == null || scene.keyDecision.options.Length < 2)
                    errors.Add($"{fileName}: scene '{scene.id}' key decision needs at least 2 options.");
            }
        }
        // Locked container: every listed chapter must hold exactly 40 scenes,
        // exactly 3 key decisions, 1 ritual, 1 sting, and 1 cliffhanger.
        foreach (var group in file.scenes.GroupBy(s => (s.season, s.chapter)).OrderBy(g => g.Key))
        {
            var key = group.Key;
            var list = group.ToList();
            if (list.Count != GameRules.ScenesPerChapter)
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} has {list.Count}/{GameRules.ScenesPerChapter} scenes.");
            var numbers = list.Select(s => s.scene).OrderBy(n => n).ToList();
            if (!numbers.SequenceEqual(Enumerable.Range(1, GameRules.ScenesPerChapter)))
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} scene numbers are not 1–{GameRules.ScenesPerChapter}.");
            var decisions = list.Where(HasKeyDecision).Select(s => s.keyDecision.number).OrderBy(n => n).ToList();
            if (!decisions.SequenceEqual(new[] { 1, 2, 3 }))
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} key decisions are [{string.Join(",", decisions)}], expected 1,2,3.");
            // Locked container: every listed chapter must hold exactly 40 scenes,
            // exactly 3 key decisions, 1 contiguous dressing-ritual group, 1 sting,
            // and 1 cliffhanger. Multi-part rituals (Season Two) are one group.
            var ritualScenes = list.Where(s => s.type == "chapter-climax").OrderBy(s => s.scene).ToList();
            int ritualGroups = 0;
            int prevScene = -2;
            foreach (var rs in ritualScenes)
            {
                if (rs.scene != prevScene + 1) ritualGroups++;
                prevScene = rs.scene;
            }
            if (ritualGroups != 1)
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} must have exactly 1 dressing ritual group, found {ritualGroups}.");
            else if (!ritualScenes.Any(s => !string.IsNullOrWhiteSpace(s.ritual?.occasionBrief)))
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} ritual group needs at least one occasion brief.");
            if (list.Count(s => s.type == "gazette-sting") != 1)
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} must have exactly 1 Gazette sting.");
            if (list.Count(s => s.type == "cliffhanger") != 1)
                errors.Add($"{fileName}: season {key.season}, chapter {key.chapter} must have exactly 1 cliffhanger.");
        }
    }

    private static void ImportScenes(string contentDir, List<string> errors)
    {
        foreach (var fileName in new[] { "scenes.json", "scenes-season2.json", "scenes-season3.json" })
        {
            var file = ReadJson<ScenesFile>(contentDir, fileName, errors);
            if (file == null) continue;
            int before = errors.Count;
            ValidateScenes(fileName, file, errors);
            if (errors.Count != before) continue;
            foreach (var scene in file.scenes) ImportScene(scene);
        }
    }

    private static void ImportScene(SceneDto scene)
    {
            var so = ScriptableObject.CreateInstance<SceneDefinitionSO>();
            so.sceneId = scene.id;
            so.season = scene.season;
            so.chapter = scene.chapter;
            so.sceneNumber = scene.scene;
            so.chapterTitle = scene.chapterTitle;
            so.chapterStatus = scene.chapterStatus;
            so.type = ParseSceneType(scene.type);
            so.synopsis = scene.synopsis;
            so.participants = scene.participants ?? Array.Empty<string>();
            so.animation = ParseSceneAnimation(scene.animation);
            so.animationNote = scene.animationNote;
            so.beatQualifier = scene.beatQualifier;
            so.playerTurns = scene.playerTurns;
            so.turnNote = scene.turnNote ?? "";
            if (HasKeyDecision(scene))
            {
                so.keyDecision = new KeyDecisionData
                {
                    number = scene.keyDecision.number,
                    title = scene.keyDecision.title,
                    options = (scene.keyDecision.options ?? Array.Empty<DecisionOptionDto>())
                        .Select(o => new DecisionOptionData { label = o.label, detail = o.detail }).ToArray()
                };
            }
            if (HasRitual(scene))
            {
                so.ritual = new RitualData
                {
                    part = scene.ritual.part ?? "",
                    occasionBrief = scene.ritual.occasionBrief ?? "",
                    directions = scene.ritual.directions ?? Array.Empty<string>(),
                    stepsSummary = scene.ritual.stepsSummary ?? "",
                    steps = scene.ritual.steps ?? Array.Empty<string>(),
                    coinPerDecision = scene.ritual.coinPerDecision,
                    coinTotal = scene.ritual.coinTotal
                };
            }
            so.fashionChoices = (scene.fashionChoices ?? Array.Empty<FashionChoiceDto>())
                .Select(c => new FashionChoiceData { label = c.label, detail = c.detail }).ToArray();
            so.sting = scene.sting ?? "";
            so.sourceFile = scene.sourceFile;
            so.coinPrice = ComputeScenePrice(scene);
            SaveDefinition("Scenes", scene.id, so);
    }

    /// <summary>
    /// LOCKED Sep 27 (Beth): price = 120 + 15 per item decision + 25 per
    /// color/finish decision + 60 if major plot point, capped at 290.
    /// Item decisions = ritual steps (non-color/finish) + fashion choices.
    /// Color/finish decisions = ritual steps naming color, fabric, finish, etc.
    /// Major plot point = scene carries a key decision.
    /// </summary>
    private static int ComputeScenePrice(SceneDto scene)
    {
        int itemDecisions = 0;
        int colorFinishDecisions = 0;

        if (scene.ritual?.steps != null)
        {
            foreach (var step in scene.ritual.steps)
            {
                if (IsColorFinishStep(step)) colorFinishDecisions++;
                else itemDecisions++;
            }
        }
        if (scene.fashionChoices != null)
            itemDecisions += scene.fashionChoices.Length;

        int price = 120 + 15 * itemDecisions + 25 * colorFinishDecisions;
        if (scene.keyDecision != null) price += 60;
        return Math.Min(290, price);
    }

    private static bool IsColorFinishStep(string step)
    {
        var lower = step.ToLowerInvariant();
        return lower.Contains("color") || lower.Contains("fabric") ||
               lower.Contains("finish") || lower.Contains("trim") ||
               lower.Contains("thread") || lower.Contains("lace") ||
               lower.Contains("embroidery");
    }

    // ------------------------------------------------------------------ vote events

    [Serializable] private sealed class VoteEventsFile
    {
        public string schemaVersion = "";
        public VoteEventDto[] voteEvents = Array.Empty<VoteEventDto>();
    }
    [Serializable] private sealed class VoteEventDto
    {
        public string id = "";
        public string date = "";
        public string gazettePrompt = "";
        public VoteLookDto lookA = new VoteLookDto();
        public VoteLookDto lookB = new VoteLookDto();
    }
    [Serializable] private sealed class VoteLookDto
    {
        public string label = "";
        public string outfitId = "";
        public string stylist = "";
    }

    private static void ValidateVoteEvents(string fileName, VoteEventsFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors)) return;
        if (file.voteEvents.Length == 0) errors.Add($"{fileName}: at least one vote event is required.");
        foreach (var vote in file.voteEvents)
        {
            if (!CheckId(fileName, vote.id, errors, "vote event")) continue;
            CheckVoteLook(fileName, vote.id, "lookA", vote.lookA, errors);
            CheckVoteLook(fileName, vote.id, "lookB", vote.lookB, errors);
        }
    }

    private static void CheckVoteLook(string fileName, string voteId, string side, VoteLookDto look, List<string> errors)
    {
        if (look == null || string.IsNullOrWhiteSpace(look.label) || string.IsNullOrWhiteSpace(look.outfitId))
            errors.Add($"{fileName}: vote '{voteId}' {side} needs a label and outfitId.");
    }

    private static void ImportVoteEvents(string contentDir, List<string> errors)
    {
        var file = ReadJson<VoteEventsFile>(contentDir, "vote-events.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateVoteEvents("vote-events.json", file, errors);
        if (errors.Count != before) return;
        foreach (var vote in file.voteEvents)
        {
            var so = ScriptableObject.CreateInstance<VoteEventDefinitionSO>();
            so.voteId = vote.id;
            so.date = vote.date;
            so.gazettePrompt = vote.gazettePrompt;
            so.lookA = ToVoteLook(vote.lookA);
            so.lookB = ToVoteLook(vote.lookB);
            SaveDefinition("VoteEvents", vote.id, so);
        }
    }

    private static VoteEventDefinitionSO.VoteLook ToVoteLook(VoteLookDto dto) =>
        new VoteEventDefinitionSO.VoteLook { label = dto.label, outfitId = dto.outfitId, stylist = dto.stylist };

    // ------------------------------------------------------------------ season passes

    [Serializable] private sealed class SeasonPassesFile
    {
        public string schemaVersion = "";
        public SeasonPassDto[] passes = Array.Empty<SeasonPassDto>();
    }
    [Serializable] private sealed class SeasonPassDto
    {
        public string id = "";
        public string displayName = "";
        public int season = 1;
        public int durationDays = 7;
        public PassTierDto[] tiers = Array.Empty<PassTierDto>();
    }
    [Serializable] private sealed class PassTierDto
    {
        public int tier;
        public int crownPrice = -1; // absent/negative = time-only, never purchasable
        public PassRewardDto[] rewards = Array.Empty<PassRewardDto>();
    }
    [Serializable] private sealed class PassRewardDto
    {
        public string rewardId = "";
        public float timeToEarnDays;
        public string earnDescription = "";
    }

    private static void ValidateSeasonPasses(string fileName, SeasonPassesFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors)) return;
        if (file.passes.Length == 0) errors.Add($"{fileName}: at least one pass is required.");
        foreach (var pass in file.passes)
        {
            if (!CheckId(fileName, pass.id, errors, "pass")) continue;
            CheckSeason(fileName, pass.id, pass.season, errors);
            if (pass.durationDays < 3 || pass.durationDays > 14)
                errors.Add($"{fileName}: pass '{pass.id}' durationDays {pass.durationDays} out of range (3–14).");
            if (pass.tiers.Length == 0)
                errors.Add($"{fileName}: pass '{pass.id}' needs at least one tier.");
            foreach (var tier in pass.tiers)
            {
                if (tier.rewards.Length == 0)
                    errors.Add($"{fileName}: pass '{pass.id}' tier {tier.tier} needs at least one reward.");
                foreach (var reward in tier.rewards)
                {
                    // Iron rule, enforced at import: every reward declares its time path.
                    if (reward.timeToEarnDays <= 0)
                        errors.Add($"{fileName}: pass '{pass.id}' reward '{reward.rewardId}' needs timeToEarnDays > 0 (iron rule).");
                    if (string.IsNullOrWhiteSpace(reward.earnDescription))
                        errors.Add($"{fileName}: pass '{pass.id}' reward '{reward.rewardId}' needs an earnDescription (iron rule).");
                }
            }
        }
    }

    private static void ImportSeasonPasses(string contentDir, List<string> errors)
    {
        var file = ReadJson<SeasonPassesFile>(contentDir, "season-passes.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateSeasonPasses("season-passes.json", file, errors);
        if (errors.Count != before) return;
        foreach (var pass in file.passes)
        {
            var so = ScriptableObject.CreateInstance<SeasonPassDefinitionSO>();
            so.passId = pass.id;
            so.displayName = pass.displayName;
            so.season = pass.season;
            so.durationDays = pass.durationDays;
            so.tiers = Array.ConvertAll(pass.tiers, t => new SeasonPassDefinitionSO.PassTier
            {
                tier = t.tier,
                purchasable = t.crownPrice >= 0,
                crownPrice = Math.Max(0, t.crownPrice),
                rewards = Array.ConvertAll(t.rewards, r => new SeasonPassDefinitionSO.PassReward
                {
                    rewardId = r.rewardId,
                    timeToEarnDays = r.timeToEarnDays,
                    earnDescription = r.earnDescription
                })
            });
            SaveDefinition("SeasonPasses", pass.id, so);
        }
    }
}
