// UNITY-DEPENDENT — requires the Unity Editor (UnityEditor + JsonUtility).
// Converts versioned Content/*.json into ScriptableObjects under
// Assets/Scripts/Runtime/Generated/. JSON is the source of truth; generated
// .asset files are git-ignored and regenerated by CI and by Beth.
//
// AI agents: this script may CREATE assets via AssetDatabase, but NEVER hand-edit
// scene/prefab YAML or GUIDs.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using ScandalSeason.Domain.Economy; // GameRules: chapters/season, scenes/chapter

public static class ContentImporter
{
    public const string ExpectedSchemaVersion = "1.0.0";
    private const string GeneratedRoot = "Assets/Scripts/Runtime/Generated";

    // ------------------------------------------------------------------ menu

    [MenuItem("Scandal Season/Import Content JSON")]
    public static void ImportAll()
    {
        var errors = new List<string>();
        string contentDir = ContentDirectory();

        ImportMergeChains(contentDir, errors);
        ImportOutfits(contentDir, errors);
        ImportScenes(contentDir, errors);
        ImportVoteEvents(contentDir, errors);
        ImportSeasonPasses(contentDir, errors);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        if (errors.Count > 0)
        {
            foreach (var e in errors) Debug.LogError($"[Content] {e}");
            Debug.LogError($"[Content] Import finished with {errors.Count} error(s). Fix Content/*.json and re-import.");
        }
        else
        {
            Debug.Log("[Content] Import complete — all files valid.");
        }

        ExitBatchMode(errors.Count);
    }

    [MenuItem("Scandal Season/Validate Content JSON")]
    public static void ValidateOnly()
    {
        var errors = new List<string>();
        string contentDir = ContentDirectory();

        ValidateFile<MergeChainsFile>(contentDir, "merge-chains.json", errors, ValidateMergeChains);
        ValidateFile<OutfitsFile>(contentDir, "outfits.json", errors, ValidateOutfits);
        ValidateFile<ScenesFile>(contentDir, "scenes.json", errors, ValidateScenes);
        ValidateFile<VoteEventsFile>(contentDir, "vote-events.json", errors, ValidateVoteEvents);
        ValidateFile<SeasonPassesFile>(contentDir, "season-passes.json", errors, ValidateSeasonPasses);

        if (errors.Count > 0)
        {
            foreach (var e in errors) Debug.LogError($"[Content] {e}");
            Debug.LogError($"[Content] Validation failed with {errors.Count} error(s).");
        }
        else Debug.Log("[Content] All content files valid.");

        ExitBatchMode(errors.Count);
    }

    // In -batchmode (CI / headless runs), surface failures as a non-zero exit
    // code so automation can fail the job. Never quits the interactive editor.
    private static void ExitBatchMode(int errorCount)
    {
        if (Application.isBatchMode)
            EditorApplication.Exit(errorCount > 0 ? 1 : 0);
    }

    // ------------------------------------------------------------------ io

    private static string ContentDirectory()
    {
        string dir = Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Content"));
        if (!Directory.Exists(dir))
            throw new DirectoryNotFoundException($"Content directory not found: {dir}");
        return dir;
    }

    private static T ReadJson<T>(string contentDir, string fileName, List<string> errors) where T : class
    {
        string path = Path.Combine(contentDir, fileName);
        if (!File.Exists(path))
        {
            errors.Add($"{fileName}: file not found.");
            return null!;
        }
        try
        {
            var parsed = JsonUtility.FromJson<T>(File.ReadAllText(path));
            if (parsed == null) errors.Add($"{fileName}: parsed to null (malformed JSON?).");
            return parsed!;
        }
        catch (Exception ex)
        {
            errors.Add($"{fileName}: JSON parse error: {ex.Message}");
            return null!;
        }
    }

    private static bool CheckSchemaVersion(string fileName, string schemaVersion, List<string> errors)
    {
        if (schemaVersion != ExpectedSchemaVersion)
        {
            errors.Add($"{fileName}: schemaVersion '{schemaVersion}' != expected '{ExpectedSchemaVersion}'.");
            return false;
        }
        return true;
    }

    // Dotted ids namespace content to its board/area (e.g. atelier.notions).
    // The literal "TBD" marks design placeholders the importer skips.
    private static readonly Regex IdPattern = new Regex(@"^([a-z0-9._-]+|TBD)$", RegexOptions.Compiled);

    private static bool CheckId(string fileName, string id, List<string> errors, string what)
    {
        if (string.IsNullOrEmpty(id) || !IdPattern.IsMatch(id))
        {
            errors.Add($"{fileName}: {what} has invalid id '{id}' (must match ^([a-z0-9._-]+|TBD)$).");
            return false;
        }
        return true;
    }

    private static bool CheckSeason(string fileName, string id, int season, List<string> errors)
    {
        // Seasons are endless (Book One is 1–10); only the lower bound is enforced.
        if (season < 1)
        {
            errors.Add($"{fileName}: '{id}' season {season} out of range (must be >= 1).");
            return false;
        }
        return true;
    }

    private static void ValidateFile<T>(string contentDir, string fileName, List<string> errors, Action<string, T, List<string>> validate) where T : class
    {
        var parsed = ReadJson<T>(contentDir, fileName, errors);
        if (parsed != null) validate(fileName, parsed, errors);
    }

    private static string EnsureFolder(string folder)
    {
        if (AssetDatabase.IsValidFolder(folder)) return folder;
        string parent = Path.GetDirectoryName(folder)!.Replace('\\', '/');
        EnsureFolder(parent);
        AssetDatabase.CreateFolder(parent, Path.GetFileName(folder));
        return folder;
    }

    private static string SanitizeAssetName(string id) =>
        Regex.Replace(id, @"[^a-zA-Z0-9-_]", "_");

    private static void SaveDefinition<T>(string subfolder, string id, T asset) where T : ScriptableObject
    {
        string folder = EnsureFolder($"{GeneratedRoot}/{subfolder}");
        string path = $"{folder}/{SanitizeAssetName(id)}.asset";
        if (AssetDatabase.LoadAssetAtPath<T>(path) != null)
            AssetDatabase.DeleteAsset(path);
        AssetDatabase.CreateAsset(asset, path);
    }

    // ------------------------------------------------------------------ merge chains

    [Serializable] private sealed class MergeChainsFile
    {
        public string schemaVersion = "";
        public MergeChainDto[] chains = Array.Empty<MergeChainDto>();
    }
    [Serializable] private sealed class MergeChainDto
    {
        public string id = "";
        public string board = "";
        public string displayName = "";
        public ChainLevelDto[] levels = Array.Empty<ChainLevelDto>();
    }
    [Serializable] private sealed class ChainLevelDto
    {
        public int level;
        public string itemId = "";
        public string name = "";
        public string displayName = "";
        public string artHook = "";
        public string art_notes = "";
        public int baseValue;
        public int unlockSeason = 1;
    }

    private static void ValidateMergeChains(string fileName, MergeChainsFile file, List<string> errors)
    {
        // Design files may not carry a schema version yet — warn, don't fail.
        if (string.IsNullOrEmpty(file.schemaVersion))
            Debug.LogWarning($"[Content] {fileName}: no schemaVersion; assuming {ExpectedSchemaVersion}.");
        else if (file.schemaVersion != ExpectedSchemaVersion)
            Debug.LogWarning($"[Content] {fileName}: schemaVersion '{file.schemaVersion}' != expected '{ExpectedSchemaVersion}'.");
        if (file.chains.Length == 0) errors.Add($"{fileName}: at least one chain is required.");
        var seenIds = new System.Collections.Generic.HashSet<string>();
        var seenItemIds = new System.Collections.Generic.HashSet<string>();
        foreach (var chain in file.chains)
        {
            if (chain.id == "TBD")
            {
                Debug.Log($"[Content] {fileName}: skipping TBD chain '{chain.displayName}' (no id assigned yet).");
                continue;
            }
            if (!CheckId(fileName, chain.id, errors, "chain")) continue;
            if (!seenIds.Add(chain.id))
                errors.Add($"{fileName}: duplicate chain id '{chain.id}'.");
            if (string.IsNullOrWhiteSpace(chain.displayName))
                errors.Add($"{fileName}: chain '{chain.id}' needs a displayName.");
            if (chain.levels.Length != 10)
                errors.Add($"{fileName}: chain '{chain.id}' must have exactly 10 levels (locked engine rule; found {chain.levels.Length}).");
            for (int i = 0; i < chain.levels.Length; i++)
            {
                var lvl = chain.levels[i];
                if (lvl.level != i + 1)
                    errors.Add($"{fileName}: chain '{chain.id}' levels must be sequential from 1 (found {lvl.level} at index {i}).");
                if (string.IsNullOrWhiteSpace(lvl.itemId))
                    errors.Add($"{fileName}: chain '{chain.id}' level {lvl.level} needs an itemId.");
                else if (!seenItemIds.Add(lvl.itemId))
                    errors.Add($"{fileName}: duplicate itemId '{lvl.itemId}' (chain '{chain.id}' level {lvl.level}).");
                if (string.IsNullOrWhiteSpace(lvl.name) && string.IsNullOrWhiteSpace(lvl.displayName))
                    errors.Add($"{fileName}: chain '{chain.id}' level {lvl.level} needs a name.");
                CheckSeason(fileName, $"{chain.id} level {lvl.level}", lvl.unlockSeason, errors);
            }
        }
    }

    private static void ImportMergeChains(string contentDir, List<string> errors)
    {
        var file = ReadJson<MergeChainsFile>(contentDir, "merge-chains.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateMergeChains("merge-chains.json", file, errors);
        if (errors.Count != before) return;
        // Content set changed (placeholder chains replaced by design chains):
        // clear previously generated chain assets so stale ones can't linger.
        foreach (var guid in AssetDatabase.FindAssets("", new[] { $"{GeneratedRoot}/MergeChains" }))
            AssetDatabase.DeleteAsset(AssetDatabase.GUIDToAssetPath(guid));
        foreach (var chain in file.chains)
        {
            if (chain.id == "TBD") continue; // logged in validation
            var so = ScriptableObject.CreateInstance<ItemChainDefinitionSO>();
            so.chainId = chain.id;
            so.board = chain.board;
            so.displayName = chain.displayName;
            so.levels = Array.ConvertAll(chain.levels, l => new ItemChainDefinitionSO.ChainLevel
            {
                level = l.level,
                itemId = l.itemId,
                displayName = !string.IsNullOrWhiteSpace(l.name) ? l.name
                    : !string.IsNullOrWhiteSpace(l.displayName) ? l.displayName
                    : $"TBD (level {l.level})",
                artHook = l.artHook,
                artNotes = l.art_notes,
                baseValue = l.baseValue,
                unlockSeason = l.unlockSeason
            });
            SaveDefinition("MergeChains", chain.id, so);
        }
    }

    // ------------------------------------------------------------------ outfits

    [Serializable] private sealed class OutfitsFile
    {
        public string schemaVersion = "";
        public OutfitCollectionDto[] collections = Array.Empty<OutfitCollectionDto>();
        public OutfitDto[] collectible_outfits = Array.Empty<OutfitDto>();
    }
    [Serializable] private sealed class OutfitCollectionDto
    {
        public string collectionId = "";
        public string title = "";
        public int group = 1;
        public string occasion = "";
        public string theme = "";
    }
    [Serializable] private sealed class OutfitDto
    {
        public string id = "";
        public string collectionId = "";
        public string name = "";
        public string rarity = "";
        public string[] garment_pieces = Array.Empty<string>();
        public string[] scoring_categories = Array.Empty<string>();
        public OutfitAcquisitionDto acquisition = new OutfitAcquisitionDto();
        public string art_notes = "";
    }
    [Serializable] private sealed class OutfitAcquisitionDto
    {
        public string free_path = "";
        public string crowns_path = "";
    }

    private static readonly System.Collections.Generic.HashSet<string> OutfitRarities =
        new System.Collections.Generic.HashSet<string> { "Common", "Fine", "Rare", "Ultra-Rare" };

    private static void ValidateOutfits(string fileName, OutfitsFile file, List<string> errors)
    {
        // Design files may not carry a schema version yet — warn, don't fail.
        if (string.IsNullOrEmpty(file.schemaVersion))
            Debug.LogWarning($"[Content] {fileName}: no schemaVersion; assuming {ExpectedSchemaVersion}.");
        else if (file.schemaVersion != ExpectedSchemaVersion)
            Debug.LogWarning($"[Content] {fileName}: schemaVersion '{file.schemaVersion}' != expected '{ExpectedSchemaVersion}'.");
        var collectionIds = new System.Collections.Generic.HashSet<string>();
        foreach (var c in file.collections)
        {
            if (!CheckId(fileName, c.collectionId, errors, "collection")) continue;
            collectionIds.Add(c.collectionId);
            if (string.IsNullOrWhiteSpace(c.title))
                errors.Add($"{fileName}: collection '{c.collectionId}' needs a title.");
        }
        if (file.collectible_outfits.Length == 0)
            errors.Add($"{fileName}: at least one collectible outfit is required.");
        var seenIds = new System.Collections.Generic.HashSet<string>();
        foreach (var outfit in file.collectible_outfits)
        {
            if (outfit.id == "TBD")
            {
                Debug.Log($"[Content] {fileName}: skipping TBD outfit '{outfit.name}' (no id assigned yet).");
                continue;
            }
            if (!CheckId(fileName, outfit.id, errors, "outfit")) continue;
            if (!seenIds.Add(outfit.id))
                errors.Add($"{fileName}: duplicate outfit id '{outfit.id}'.");
            if (string.IsNullOrWhiteSpace(outfit.name))
                errors.Add($"{fileName}: outfit '{outfit.id}' needs a name.");
            if (!collectionIds.Contains(outfit.collectionId))
                errors.Add($"{fileName}: outfit '{outfit.id}' references unknown collection '{outfit.collectionId}'.");
            if (!OutfitRarities.Contains(outfit.rarity))
                errors.Add($"{fileName}: outfit '{outfit.id}' has unknown rarity '{outfit.rarity}'.");
            if (outfit.garment_pieces.Length == 0)
                errors.Add($"{fileName}: outfit '{outfit.id}' needs at least one garment piece.");
            if (outfit.acquisition == null || string.IsNullOrWhiteSpace(outfit.acquisition.free_path))
                errors.Add($"{fileName}: outfit '{outfit.id}' needs an acquisition free_path.");
        }
    }

    private static OutfitSlot ParseOutfitSlot(string slot) => slot switch
    {
        "dress" => OutfitSlot.Dress,
        "hair" => OutfitSlot.Hair,
        "accessory" => OutfitSlot.Accessory,
        "shoes" => OutfitSlot.Shoes,
        "jewelry" => OutfitSlot.Jewelry,
        _ => throw new ArgumentException($"Unknown outfit slot '{slot}'.")
    };

    private static void ImportOutfits(string contentDir, List<string> errors)
    {
        var file = ReadJson<OutfitsFile>(contentDir, "outfits.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateOutfits("outfits.json", file, errors);
        if (errors.Count != before) return;
        // Content set changed (placeholder outfits replaced by design outfits):
        // clear previously generated outfit assets so stale ones can't linger.
        foreach (var guid in AssetDatabase.FindAssets("", new[] { $"{GeneratedRoot}/Outfits" }))
            AssetDatabase.DeleteAsset(AssetDatabase.GUIDToAssetPath(guid));
        foreach (var outfit in file.collectible_outfits)
        {
            if (outfit.id == "TBD") continue; // logged in validation
            var so = ScriptableObject.CreateInstance<OutfitDefinitionSO>();
            so.outfitId = outfit.id;
            so.displayName = outfit.name;
            so.collectionId = outfit.collectionId;
            so.rarity = outfit.rarity;
            so.season = 1; // Group 1 is Season 1 content; later groups map to seasons when designed
            so.garmentPieces = outfit.garment_pieces;
            so.categories = outfit.scoring_categories;
            so.acquisition = new OutfitDefinitionSO.OutfitAcquisition
            {
                freePath = outfit.acquisition.free_path,
                crownsPath = outfit.acquisition.crowns_path
            };
            so.artNotes = outfit.art_notes;
            SaveDefinition("Outfits", outfit.id, so);
        }
    }

    // ------------------------------------------------------------------ scenes

    [Serializable] private sealed class ScenesFile
    {
        public string schemaVersion = "";
        public SceneDto[] scenes = Array.Empty<SceneDto>();
    }
    [Serializable] private sealed class SceneDto
    {
        public string id = "";
        public int season = 1;
        public int chapter = 1;
        public string type = "";
        public string title = "";
        public string synopsis = "";
        public int energyCost;
        public string briefId = "";
        public string stakes = "";
    }

    private static SceneType ParseSceneType(string type) => type switch
    {
        "dialogue" => SceneType.Dialogue,
        "fashion-selection" => SceneType.FashionSelection,
        "chapter-climax" => SceneType.ChapterClimax,
        _ => throw new ArgumentException($"Unknown scene type '{type}'.")
    };

    private static void ValidateScenes(string fileName, ScenesFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors)) return;
        if (file.scenes.Length == 0) errors.Add($"{fileName}: at least one scene is required.");
        foreach (var scene in file.scenes)
        {
            if (!CheckId(fileName, scene.id, errors, "scene")) continue;
            CheckSeason(fileName, scene.id, scene.season, errors);
            if (scene.chapter < 1 || scene.chapter > GameRules.ChaptersPerSeason)
                errors.Add($"{fileName}: scene '{scene.id}' chapter {scene.chapter} out of range (1–{GameRules.ChaptersPerSeason}).");
            if (string.IsNullOrWhiteSpace(scene.title))
                errors.Add($"{fileName}: scene '{scene.id}' needs a title.");
            SceneType parsed;
            try { parsed = ParseSceneType(scene.type); }
            catch { errors.Add($"{fileName}: scene '{scene.id}' has unknown type '{scene.type}'."); continue; }
            if (parsed == SceneType.FashionSelection && string.IsNullOrWhiteSpace(scene.briefId))
                errors.Add($"{fileName}: fashion-selection scene '{scene.id}' requires briefId.");
            if (parsed == SceneType.ChapterClimax && string.IsNullOrWhiteSpace(scene.stakes))
                errors.Add($"{fileName}: chapter-climax scene '{scene.id}' requires stakes.");
            if (scene.energyCost < 0)
                errors.Add($"{fileName}: scene '{scene.id}' energyCost cannot be negative.");
        }
        // Completeness check (warning only — content is authored incrementally):
        // the locked 30×40 rule wants 40 scenes per chapter per season.
        foreach (var group in file.scenes.GroupBy(s => (s.season, s.chapter)).OrderBy(g => g.Key))
        {
            if (group.Count() < GameRules.ScenesPerChapter)
                Debug.LogWarning($"{fileName}: season {group.Key.season}, chapter {group.Key.chapter} " +
                    $"has {group.Count()}/{GameRules.ScenesPerChapter} scenes (30×40 rule target).");
        }
    }

    private static void ImportScenes(string contentDir, List<string> errors)
    {
        var file = ReadJson<ScenesFile>(contentDir, "scenes.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateScenes("scenes.json", file, errors);
        if (errors.Count != before) return;
        foreach (var scene in file.scenes)
        {
            var so = ScriptableObject.CreateInstance<SceneDefinitionSO>();
            so.sceneId = scene.id;
            so.season = scene.season;
            so.chapter = scene.chapter;
            so.type = ParseSceneType(scene.type);
            so.title = scene.title;
            so.synopsis = scene.synopsis;
            so.energyCost = scene.energyCost;
            so.briefId = scene.briefId;
            so.stakes = scene.stakes;
            SaveDefinition("Scenes", scene.id, so);
        }
    }

    // ------------------------------------------------------------------ vote events

    [Serializable] private sealed class VoteEventsFile
    {
        public string schemaVersion = "";
        public VoteEventDto[] voteEvents = Array.Empty<VoteEventDto>();
    }
    [Serializable] private sealed class VoteEventDto
    {
        public string id = "";
        public string date = "";
        public string gazettePrompt = "";
        public VoteLookDto lookA = new VoteLookDto();
        public VoteLookDto lookB = new VoteLookDto();
    }
    [Serializable] private sealed class VoteLookDto
    {
        public string label = "";
        public string outfitId = "";
        public string stylist = "";
    }

    private static void ValidateVoteEvents(string fileName, VoteEventsFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors)) return;
        if (file.voteEvents.Length == 0) errors.Add($"{fileName}: at least one vote event is required.");
        foreach (var vote in file.voteEvents)
        {
            if (!CheckId(fileName, vote.id, errors, "vote event")) continue;
            CheckVoteLook(fileName, vote.id, "lookA", vote.lookA, errors);
            CheckVoteLook(fileName, vote.id, "lookB", vote.lookB, errors);
        }
    }

    private static void CheckVoteLook(string fileName, string voteId, string side, VoteLookDto look, List<string> errors)
    {
        if (look == null || string.IsNullOrWhiteSpace(look.label) || string.IsNullOrWhiteSpace(look.outfitId))
            errors.Add($"{fileName}: vote '{voteId}' {side} needs a label and outfitId.");
    }

    private static void ImportVoteEvents(string contentDir, List<string> errors)
    {
        var file = ReadJson<VoteEventsFile>(contentDir, "vote-events.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateVoteEvents("vote-events.json", file, errors);
        if (errors.Count != before) return;
        foreach (var vote in file.voteEvents)
        {
            var so = ScriptableObject.CreateInstance<VoteEventDefinitionSO>();
            so.voteId = vote.id;
            so.date = vote.date;
            so.gazettePrompt = vote.gazettePrompt;
            so.lookA = ToVoteLook(vote.lookA);
            so.lookB = ToVoteLook(vote.lookB);
            SaveDefinition("VoteEvents", vote.id, so);
        }
    }

    private static VoteEventDefinitionSO.VoteLook ToVoteLook(VoteLookDto dto) =>
        new VoteEventDefinitionSO.VoteLook { label = dto.label, outfitId = dto.outfitId, stylist = dto.stylist };

    // ------------------------------------------------------------------ season passes

    [Serializable] private sealed class SeasonPassesFile
    {
        public string schemaVersion = "";
        public SeasonPassDto[] passes = Array.Empty<SeasonPassDto>();
    }
    [Serializable] private sealed class SeasonPassDto
    {
        public string id = "";
        public string displayName = "";
        public int season = 1;
        public int durationDays = 7;
        public PassTierDto[] tiers = Array.Empty<PassTierDto>();
    }
    [Serializable] private sealed class PassTierDto
    {
        public int tier;
        public int crownPrice = -1; // absent/negative = time-only, never purchasable
        public PassRewardDto[] rewards = Array.Empty<PassRewardDto>();
    }
    [Serializable] private sealed class PassRewardDto
    {
        public string rewardId = "";
        public float timeToEarnDays;
        public string earnDescription = "";
    }

    private static void ValidateSeasonPasses(string fileName, SeasonPassesFile file, List<string> errors)
    {
        if (!CheckSchemaVersion(fileName, file.schemaVersion, errors)) return;
        if (file.passes.Length == 0) errors.Add($"{fileName}: at least one pass is required.");
        foreach (var pass in file.passes)
        {
            if (!CheckId(fileName, pass.id, errors, "pass")) continue;
            CheckSeason(fileName, pass.id, pass.season, errors);
            if (pass.durationDays < 3 || pass.durationDays > 14)
                errors.Add($"{fileName}: pass '{pass.id}' durationDays {pass.durationDays} out of range (3–14).");
            if (pass.tiers.Length == 0)
                errors.Add($"{fileName}: pass '{pass.id}' needs at least one tier.");
            foreach (var tier in pass.tiers)
            {
                if (tier.rewards.Length == 0)
                    errors.Add($"{fileName}: pass '{pass.id}' tier {tier.tier} needs at least one reward.");
                foreach (var reward in tier.rewards)
                {
                    // Iron rule, enforced at import: every reward declares its time path.
                    if (reward.timeToEarnDays <= 0)
                        errors.Add($"{fileName}: pass '{pass.id}' reward '{reward.rewardId}' needs timeToEarnDays > 0 (iron rule).");
                    if (string.IsNullOrWhiteSpace(reward.earnDescription))
                        errors.Add($"{fileName}: pass '{pass.id}' reward '{reward.rewardId}' needs an earnDescription (iron rule).");
                }
            }
        }
    }

    private static void ImportSeasonPasses(string contentDir, List<string> errors)
    {
        var file = ReadJson<SeasonPassesFile>(contentDir, "season-passes.json", errors);
        if (file == null) return;
        int before = errors.Count;
        ValidateSeasonPasses("season-passes.json", file, errors);
        if (errors.Count != before) return;
        foreach (var pass in file.passes)
        {
            var so = ScriptableObject.CreateInstance<SeasonPassDefinitionSO>();
            so.passId = pass.id;
            so.displayName = pass.displayName;
            so.season = pass.season;
            so.durationDays = pass.durationDays;
            so.tiers = Array.ConvertAll(pass.tiers, t => new SeasonPassDefinitionSO.PassTier
            {
                tier = t.tier,
                purchasable = t.crownPrice >= 0,
                crownPrice = Math.Max(0, t.crownPrice),
                rewards = Array.ConvertAll(t.rewards, r => new SeasonPassDefinitionSO.PassReward
                {
                    rewardId = r.rewardId,
                    timeToEarnDays = r.timeToEarnDays,
                    earnDescription = r.earnDescription
                })
            });
            SaveDefinition("SeasonPasses", pass.id, so);
        }
    }
}
