// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// Game logic lives in ScandalSeason.Domain. Generated by the content importer;
// AI agents: do NOT hand-edit the generated .asset YAML.

using UnityEngine;

[CreateAssetMenu(fileName = "MergeChain", menuName = "Scandal Season/Merge Chain")]
public sealed class ItemChainDefinitionSO : ScriptableObject
{
    [Tooltip("Matches chain.id in Content/merge-chains.json")]
    public string chainId = "";
    [Tooltip("Board namespace this chain belongs to (e.g. atelier, park)")]
    public string board = "";
    public string displayName = "";
    public ChainLevel[] levels = System.Array.Empty<ChainLevel>();

    [System.Serializable]
    public sealed class ChainLevel
    {
        public int level;
        [Tooltip("Unique item id for this level (unique across all chains)")]
        public string itemId = "";
        public string displayName = "";
        [Tooltip("Canonical art hook from the design package")]
        public string artHook = "";
        [Tooltip("Art hook / itemId / detailing notes from the design package")]
        public string artNotes = "";
        [Tooltip("Base merge/economy value; design uses 1..512 doubling")]
        public int baseValue;
        public int unlockSeason = 1;
    }
}
