// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// Game logic lives in ScandalSeason.Domain. Generated by the content importer;
// AI agents: do NOT hand-edit the generated .asset YAML.
// Rewards are outfits/hair/accessories — NEVER avatar unlocks.

using UnityEngine;

public enum OutfitSlot
{
    Dress,
    Hair,
    Accessory,
    Shoes,
    Jewelry
}

[CreateAssetMenu(fileName = "Outfit", menuName = "Scandal Season/Outfit")]
public sealed class OutfitDefinitionSO : ScriptableObject
{
    [Tooltip("Matches outfit.id in Content/outfits.json")]
    public string outfitId = "";
    public string displayName = "";
    [Tooltip("Book One is seasons 1–10; seasons continue indefinitely after it.")]
    public int season = 1;
    [Tooltip("Special-edition outfits are the critical monetization lever — but every one keeps a credible free path.")]
    public bool specialEdition;
    public OutfitPiece[] pieces = System.Array.Empty<OutfitPiece>();
    [Tooltip("Scoring category ids. Categories are visible to players; weights stay hidden server-side.")]
    public string[] categories = System.Array.Empty<string>();

    [System.Serializable]
    public sealed class OutfitPiece
    {
        public OutfitSlot slot;
        public string itemId = "";
        public string displayName = "";
    }
}
