// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// Game logic lives in ScandalSeason.Domain. Generated by the content importer;
// AI agents: do NOT hand-edit the generated .asset YAML.
// Rewards are outfits/hair/accessories — NEVER avatar unlocks.
//
// Wardrobe v2 (locked Sep 27 2026): dual-unit wardrobe. Every ensemble is a
// named set of ritual-tagged components. Components are the chapter-dressing
// (story-side) unit; the ensemble is the Daily Vote (competition-side) unit.
// Rarity tiers: Atelier / Couture / Impériale / Légende.

using UnityEngine;

public sealed class OutfitDefinitionSO : ScriptableObject
{
    [Tooltip("Matches ensemble.id in Content/outfits.json")]
    public string outfitId = "";
    public string displayName = "";
    [Tooltip("Closet collection this ensemble belongs to (e.g. closet.morning_room)")]
    public string collectionId = "";
    [Tooltip("Atelier / Couture / Impériale / Légende")]
    public string rarity = "";
    [Tooltip("Book One is seasons 1–10; seasons continue indefinitely after it.")]
    public int season = 1;
    [Tooltip("Time-only ensembles are earned, never purchasable, never returning (e.g. the Triumph Gown).")]
    public bool timeless;
    [Tooltip("Modiste who made the ensemble")]
    public string modisteName = "";
    [Tooltip("The modiste's voice, from the design package")]
    public string modisteVoice = "";
    [Tooltip("Ensemble lore, in the modiste's voice")]
    public string ensembleStory = "";
    [Tooltip("Ritual-tagged garment components — the chapter-dressing unit")]
    public OutfitComponent[] components = System.Array.Empty<OutfitComponent>();
    [Tooltip("Completion payoff text for the Atelier Album portrait moment")]
    public string portraitMoment = "";
    [Tooltip("Harmony bonus label, e.g. +3% presentation in Daily Vote for 3+ pieces (Daily Vote only)")]
    public string harmonyBonus = "";
    [Tooltip("How the ensemble is earned; crownsPath is prose and may state no purchasable path exists (time-only).")]
    public OutfitAcquisition acquisition = new OutfitAcquisition();

    [System.Serializable]
    public sealed class OutfitAcquisition
    {
        public string freePath = "";
        public string crownsPath = "";
    }

    [System.Serializable]
    public sealed class OutfitComponent
    {
        public string componentId = "";
        public string displayName = "";
        [Tooltip("Ritual part: bodice / sleeves / skirt / neckline / trim / shoes / hair / accessory")]
        public string ritualPart = "";
        public string lore = "";
        public string baseFabric = "";
        public string baseColor = "";
        public string recolorName = "";
        public string recolorFabric = "";
        public string recolorColor = "";
        public string[] dyePalette = System.Array.Empty<string>();
    }
}
