// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// A scene is a flexible story beat, not a fixed unit. Generated by the content
// importer from Content/scenes.json (schema v2.0.0); AI agents: do NOT hand-edit
// the generated .asset YAML.
//
// Key decisions record their options and remembered means; the game tracks
// tone/relationship/verdict flavor from these — never branch-tree plot state.

using System;
using UnityEngine;

public enum SceneType
{
    Dialogue,        // dialogue-heavy beat
    FashionSelection, // diegetic 2–3 option beat (no coin cost; the game remembers)
    ChapterClimax,   // the one-per-chapter dressing-for-climax ritual
    Texture,         // texture micro-beat
    PlotBeat,        // ordinary (untagged) plot beat
    GazetteSting,    // Bell's verdict sting
    Cliffhanger      // chapter-closing hook
}

public enum SceneAnimation
{
    Shared, // reusable staging
    Custom  // bespoke animation; tentpole set-pieces plus signed-off signature beats
}

[Serializable]
public sealed class DecisionOptionData
{
    public string label = "";
    [TextArea] public string detail = "";
}

[Serializable]
public sealed class KeyDecisionData
{
    [Tooltip("1, 2, or 3 — each chapter carries exactly three marked key decisions.")]
    public int number;
    public string title = "";
    [Tooltip("Choices may converge on the same outcome through different means; the game remembers the means.")]
    public DecisionOptionData[] options = Array.Empty<DecisionOptionData>();
}

[Serializable]
public sealed class RitualData
{
    [TextArea] public string occasionBrief = "";
    [Tooltip("The ritual's directions (always 3 in Season One).")]
    public string[] directions = Array.Empty<string>();
    [TextArea] public string stepsSummary = "";
    public string[] steps = Array.Empty<string>();
    public int coinPerDecision;
    public int coinTotal;
}

[Serializable]
public sealed class FashionChoiceData
{
    public string label = "";
    [TextArea] public string detail = "";
}

[CreateAssetMenu(fileName = "Scene", menuName = "Scandal Season/Scene")]
public sealed class SceneDefinitionSO : ScriptableObject
{
    [Tooltip("Matches scene.id in Content/scenes.json (e.g. s1-c4-s12).")]
    public string sceneId = "";
    [Tooltip("Book One is seasons 1–10; seasons continue indefinitely after it.")]
    public int season = 1;
    public int chapter = 1;
    [Tooltip("Scene number within the chapter (1–40).")]
    public int sceneNumber = 1;
    public string chapterTitle = "";
    [Tooltip("FULL = signed-off build source; PILOT = format pilot, not yet locked.")]
    public string chapterStatus = "";
    public SceneType type;
    [Tooltip("The scene's Purpose line from the chapter file.")]
    [TextArea] public string synopsis = "";
    public string[] participants = Array.Empty<string>();
    public SceneAnimation animation;
    [Tooltip("Bespoke reason for a Custom call, or a Shared staging note.")]
    public string animationNote = "";
    [Tooltip("Optional qualifier from the scene header, e.g. 'villain' on plot beats.")]
    public string beatQualifier = "";
    [Tooltip("Null unless this scene carries one of the chapter's three marked key decisions.")]
    public KeyDecisionData keyDecision;
    [Tooltip("Null unless this scene is the chapter's dressing ritual.")]
    public RitualData ritual;
    [Tooltip("Diegetic fashion options; empty for remembered-only beats and non-fashion scenes.")]
    public FashionChoiceData[] fashionChoices = Array.Empty<FashionChoiceData>();
    [Tooltip("Bell's Gazette sting text; set on gazette-sting scenes.")]
    [TextArea] public string sting = "";
    [Tooltip("Repo-relative chapter .md this scene was parsed from.")]
    public string sourceFile = "";
}
