// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// A scene is a flexible story beat, not a fixed unit. Generated by the content
// importer; AI agents: do NOT hand-edit the generated .asset YAML.

using UnityEngine;

public enum SceneType
{
    Dialogue,        // dialogue-heavy beat
    FashionSelection, // player dresses to a brief
    ChapterClimax     // dressing for the chapter climax; carries real stakes
}

[CreateAssetMenu(fileName = "Scene", menuName = "Scandal Season/Scene")]
public sealed class SceneDefinitionSO : ScriptableObject
{
    [Tooltip("Matches scene.id in Content/scenes.json")]
    public string sceneId = "";
    [Tooltip("Book One is seasons 1–10; seasons continue indefinitely after it.")]
    public int season = 1;
    public int chapter = 1;
    public SceneType type;
    public string title = "";
    [TextArea] public string synopsis = "";
    [Tooltip("Energy cost to play. Energy is the only throttle; plot is never time-gated.")]
    public int energyCost;
    [Tooltip("Required for FashionSelection: the styling brief the player dresses to.")]
    public string briefId = "";
    [Tooltip("Required for ChapterClimax: what is genuinely at risk in this scene.")]
    [TextArea] public string stakes = "";
}
