// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// Event passes run 3–14 days. Every reward declares its time/engagement path
// (iron rule — enforced in schema AND by CatalogValidator). Generated by the
// content importer; AI agents: do NOT hand-edit the generated .asset YAML.

using UnityEngine;

[CreateAssetMenu(fileName = "SeasonPass", menuName = "Scandal Season/Season Pass")]
public sealed class SeasonPassDefinitionSO : ScriptableObject
{
    [Tooltip("Matches pass.id in Content/season-passes.json")]
    public string passId = "";
    public string displayName = "";
    [Tooltip("Book One is seasons 1–10; seasons continue indefinitely after it.")]
    public int season = 1;
    [Range(3, 14)] public int durationDays = 7;
    public PassTier[] tiers = System.Array.Empty<PassTier>();

    [System.Serializable]
    public sealed class PassTier
    {
        public int tier;
        [Tooltip("When false, this tier is time-only: never purchasable at any price.")]
        public bool purchasable;
        public int crownPrice;
        public PassReward[] rewards = System.Array.Empty<PassReward>();
    }

    [System.Serializable]
    public sealed class PassReward
    {
        public string rewardId = "";
        [Tooltip("Days of engagement to earn this reward with time alone.")]
        public float timeToEarnDays;
        [Tooltip("Human-readable free path, e.g. 'Complete 5 Daily Votes'.")]
        public string earnDescription = "";
    }
}
