// UNITY-DEPENDENT — UnityEngine ScriptableObject (thin data holder).
// Daily Vote: two looks side-by-side, votes totaled. No brackets, no VS mode.
// Generated by the content importer; AI agents: do NOT hand-edit the generated .asset YAML.

using UnityEngine;

[CreateAssetMenu(fileName = "VoteEvent", menuName = "Scandal Season/Vote Event")]
public sealed class VoteEventDefinitionSO : ScriptableObject
{
    [Tooltip("Matches voteEvent.id in Content/vote-events.json")]
    public string voteId = "";
    public string date = "";
    [TextArea] public string gazettePrompt = "";
    public VoteLook lookA = new VoteLook();
    public VoteLook lookB = new VoteLook();

    [System.Serializable]
    public sealed class VoteLook
    {
        public string label = "";
        [Tooltip("References outfit.id in Content/outfits.json")]
        public string outfitId = "";
        public string stylist = "";
    }
}
